### PR TITLE
Use openjdk-*-jre-headless packages for jre images

### LINKED ISSUE #21: Headless variant
Would it make sense for the JRE images to install the `openjdk-*-jre-headless` variants instead? I actually hate the idea of having more 2x as many variants of the `java` image, so that's not what I'm suggesting.

Folks who actually need a non-headless JRE in a Docker container could install the `openjdk-*-jre` themselves and pick up the additional functionality and dependencies.

### PR DESCRIPTION
**Pull request by md5**
Figured I may as well create a PR for this change. Feel free to close if you're not interested.

Fixes #21

### CODE REVIEW

**Comment by md5** [comment]
Here's a list of [the actual files](https://packages.debian.org/sid/amd64/openjdk-8-jre/filelist) added in the Debian `openjdk-8-jre` package for `amd64`:

```
/usr/lib/jvm/java-8-openjdk-amd64/bin/policytool
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libicedtea-sound.so
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjsoundalsa.so
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libsplashscreen.so
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/libatk-wrapper.so
/usr/lib/jvm/java-8-openjdk-amd64/jre/man/ja_JP.UTF-8/man1/policytool.1.gz
/usr/lib/jvm/java-8-openjdk-amd64/jre/man/man1/policytool.1.gz
/usr/lib/jvm/java-8-openjdk-amd64/man/ja_JP.UTF-8/man1/policytool.1.gz
/usr/lib/jvm/java-8-openjdk-amd64/man/man1/policytool.1.gz
/usr/share/application-registry/openjdk-8-archive.applications
/usr/share/applications/openjdk-8-java.desktop
/usr/share/applications/openjdk-8-policytool.desktop
/usr/share/doc/openjdk-8-jre
/usr/share/lintian/overrides/openjdk-8-jre
/usr/share/mime-info/openjdk-8-archive.keys
/usr/share/mime-info/openjdk-8-archive.mime
/usr/share/pixmaps/openjdk-8.xpm
```

Besides those files, the `openjdk-*-jre` packages pull in the corresponding `-headless` package and bits necessary to run the GUI.

I was a bit worried at first that it wasn't installing stuff like `libpng12-0` anymore, but I satisfied my curiousity with this test program:

```java
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

public class Test {
	public static void main(String... argz) throws Exception {
		BufferedImage bi = new BufferedImage(100, 100, BufferedImage.TYPE_INT_ARGB);
		File outputfile = new File("test.png");
		ImageIO.write(bi, "png", outputfile);
	}
}
```

I build it like so:

> $ docker run -it --rm -v $(pwd):/src -w /src java:openjdk-8-jdk javac Test.java

And ran it like so:

> $ docker run -it --rm -v $(pwd):/src -w /src java:openjdk-8-jre-headless java -cp . Test

It produced an image without any exceptions.

**Comment by md5** [comment]
I just discovered that this originally used `-headless` and changed to the other package less than a week ago in 0b124de91ebd32bcc8977fd2214d36b8fccb615c.

@tianon?

**Comment by tianon** [comment]
facepalm; good catch

**Comment by tianon** [comment]
+1 LGTM

**Comment by yosifkit** [comment]
LGTM

**Comment by md5** [comment]
:sunny:

**Comment by md5** [comment]
The diff between what's currently live on the Docker Registry and what's on master looks correct now: https://github.com/docker-library/java/compare/2408508f3b000bf997febbdb90a861185a64a260...58866569ecc3d516467baf83375f3bd4cb0b8229

**Pull request merged**
