### PR TITLE
Update to use buildpack-deps:*-micro as the base

### LINKED ISSUE #17: use base library/buildpack-deps
It would be nice if the Java images could use `library/buildpack-deps` as the base image. Most of the language stacks use this base image, and it would be nice to have consistency. This image also comes with some useful utilities, such as git, which can be helpful when using the image as part of a build process.

### PR DESCRIPTION
**Pull request by tianon**
Fixes #17

### CODE REVIEW

**Comment by yosifkit** [comment]
you should to drop `curl` and `wget` since they are in micro. :smile:

**Comment by tianon** [comment]
Sssh, don't judge me.

**Comment by tianon** [comment]
Doing a build test now to make sure I didn't break anything in my refactoring.

**Comment by tianon** [comment]
:+1:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
