### PR TITLE
Use Debian Stretch as base image for Java 8

### PR DESCRIPTION
**Pull request by md5**

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
I'm torn on this one.  In theory, Stretch means less "unstable", but in practice, it really just means we have to wait for package migration to get new versions of OpenJDK. :confused:

**Comment by md5** [comment]
@tianon No rush. I figured that opening the PR wouldn't hurt either way since this change will need to happen at some point. Feel free to let it ferment for a bit.

**Comment by md5** [comment]
It probably makes sense to close this in favor of #40.

**Pull request closed without merging**
