### PR TITLE
Update to use the new *-scm and *-curl buildpack-deps variants

### PR DESCRIPTION
**Pull request by tianon**
See https://github.com/docker-library/official-images/pull/413.

### CODE REVIEW

**Comment by yosifkit** [comment]
Do you want to throw in the ca-certs fix for java-8 too? Otherwise, LGTM

**Comment by tianon** [comment]
I was thinking that should be a separate PR.  I'm testing this one now (but building the buildpack-deps variants first so that it can build correctly).

**Comment by yosifkit** [comment]
:+1:

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh | sed 's/docker-library/infosiftr/' > java
$ bashbrew build ./java
Processing java:openjdk-6b33-jdk ...
Processing java:openjdk-6b33 ...
Processing java:openjdk-6-jdk ...
Processing java:openjdk-6 ...
Processing java:6b33-jdk ...
Processing java:6b33 ...
Processing java:6-jdk ...
Processing java:6 ...
Processing java:openjdk-6b33-jre ...
Processing java:openjdk-6-jre ...
Processing java:6b33-jre ...
Processing java:6-jre ...
Processing java:openjdk-7u71-jdk ...
Processing java:openjdk-7u71 ...
Processing java:openjdk-7-jdk ...
Processing java:openjdk-7 ...
Processing java:7u71-jdk ...
Processing java:7u71 ...
Processing java:7-jdk ...
Processing java:7 ...
Processing java:jdk ...
Processing java:latest ...
Processing java:openjdk-7u71-jre ...
Processing java:openjdk-7-jre ...
Processing java:7u71-jre ...
Processing java:7-jre ...
Processing java:jre ...
Processing java:openjdk-8u40-b09-jdk ...
Processing java:openjdk-8u40-b09 ...
Processing java:openjdk-8u40-jdk ...
Processing java:openjdk-8u40 ...
Processing java:openjdk-8-jdk ...
Processing java:openjdk-8 ...
Processing java:8u40-b09-jdk ...
Processing java:8u40-b09 ...
Processing java:8u40-jdk ...
Processing java:8u40 ...
Processing java:8-jdk ...
Processing java:8 ...
Processing java:openjdk-8u40-b09-jre ...
Processing java:openjdk-8u40-jre ...
Processing java:openjdk-8-jre ...
Processing java:8u40-b09-jre ...
Processing java:8u40-jre ...
Processing java:8-jre ...
$ docker images java
REPOSITORY          TAG                    IMAGE ID            CREATED             VIRTUAL SIZE
java                openjdk-8-jre          6f6685eb301a        51 minutes ago      521.6 MB
java                openjdk-8-jdk          0761ce966d25        57 minutes ago      638.8 MB
java                openjdk-7-jre          ce5816932b7b        About an hour ago   486.5 MB
java                openjdk-7-jdk          c390fbd67fd6        About an hour ago   584.6 MB
java                openjdk-6-jre          6be7fb1be1b6        About an hour ago   304.3 MB
java                openjdk-6-jdk          d9790507bc7b        About an hour ago   418.9 MB
```

**Comment by yosifkit** [comment]
LGTM

**Comment by psftw** [comment]
This effectively takes SCM tools out of the jre tags, right?  I don't think people should depend on that (WHY BINARY IN YOUR SCM?), but there are images that depend on java:X-jre, which makes me wonder how many people would be "hit" by the change.  @cpuguy83 I think the jruby image may need to use jdk now or add the SCM tools needed by gem (sorry, not very familiar with gem)?

Maybe it is worth pointing out this difference in the docs to be extra clear that jre doesn't include SCM tools?

**Comment by yosifkit** [comment]
Actually, since we never actually built and pushed the one based on `-micro`, jre has not had SCM tools.  We had looked at the size changes and were a little baffled, so we made this to fix it.

**Comment by cpuguy83** [comment]
Yeah, no version of jruby has depended on jre before, that change is pending.
Actually would prefer to not have SCM tools anyhow.

**Comment by psftw** [comment]
Ahh, sorry for my confusion there; I was mixing PRs and git checkouts in bashbrew/src trying to be slick :octocat:

**Comment by tianon** [comment]
Keep trying to be slick, Peter; the dialogue itself is helpful, especially
when the intentions are in the right place and the discussion is
level-headed. ♥

**Pull request merged**
